# Generated by Django 6.0 on 2025-12-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('author', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('SN', 'SCIENCE'), ('HC', 'HISTORICAL'), ('ST', 'STORY')], max_length=2)),
            ],
        ),
    ]
